from sklearn.pipeline import Pipeline

from src.features.transformers import DayPhaseTransformer, DropColumnsTransformer, ExtractColumnsTransformer, FillPropertyNaNsTransformer, GetDummiesTransformer, \
    PropertyOutlierTransformer, StandardScalerTransformer, Log1pTransformer

columns_to_extract = [
    'p_num',
    'day_phase',
    'bg-0:00',
    'bg-0:05',
    'bg-0:10',
    'bg-0:15',
    'bg-0:20',
    'bg-0:25',
    'bg-0:30',
    'bg-0:35',
    'bg-0:40',
    'bg-0:45',
    'bg-0:50',
    'bg-0:55',
    'bg-1:00',
    'bg-1:05',
    'bg-1:10',
    'bg-1:15',
    'bg-1:20',
    'bg-1:25',
    'bg-1:30',
    'bg-1:35',
    'bg-1:40',
    'bg-1:45',
    'bg-1:50',
    'bg-1:55',
    'bg-2:00',
    'insulin-0:00',
    'insulin-0:05',
    'insulin-0:10',
    'insulin-0:15',
    'insulin-0:20',
    'insulin-0:25',
    'insulin-0:30',
    'insulin-0:35',
    'insulin-0:40',
    'insulin-0:45',
    'insulin-0:50',
    'insulin-0:55',
    'insulin-1:00',
    'insulin-1:05',
    'insulin-1:10',
    'insulin-1:15',
    'insulin-1:20',
    'insulin-1:25',
    'insulin-1:30',
    'insulin-1:35',
    'insulin-1:40',
    'insulin-1:45',
    'insulin-1:50',
    'insulin-1:55',
    'insulin-2:00',
    'cals-0:00',
    'cals-0:05',
    'cals-0:10',
    'cals-0:15',
    'cals-0:20',
    'cals-0:25',
    'cals-0:30',
    'cals-0:35',
    'cals-0:40',
    'cals-0:45',
    'cals-0:50',
    'cals-0:55',
    'cals-1:00',
    'cals-1:05',
    'cals-1:10',
    'cals-1:15',
    'cals-1:20',
    'cals-1:25',
    'cals-1:30',
    'cals-1:35',
    'cals-1:40',
    'cals-1:45',
    'cals-1:50',
    'cals-1:55',
    'cals-2:00',
    'bg+1:00'
]

preprocessing_pipeline = Pipeline(steps=[
    ('day_phase', DayPhaseTransformer(time_column='time', time_format='%H:%M:%S', result_column='day_phase', ignore_errors=True)),
    ('drop_parameter_cols', DropColumnsTransformer(starts_with=['activity', 'carbs', 'steps', 'hr'])),
    ('drop_others', DropColumnsTransformer(columns_to_delete=['time'])),
    ('fill_properties_nan_bg', FillPropertyNaNsTransformer(parameter='bg', how=['interpolate', 'median'])),
    ('fill_properties_nan_insulin', FillPropertyNaNsTransformer(parameter='insulin', how=['median'])),
    ('drop_outliers', PropertyOutlierTransformer(parameter='insulin', filter_function=lambda x: x < 0, fill_strategy='zero')),
    ('extract_features', ExtractColumnsTransformer(columns_to_extract=columns_to_extract)),
])

standardization_pipeline = Pipeline(steps=[
    ('get_dummies', GetDummiesTransformer(columns=['day_phase'])),
    ('log_transformer', Log1pTransformer(columns=columns_to_extract[2:-1])),
    ('standard_scaler', StandardScalerTransformer(columns=columns_to_extract[2:-1]))
])

pipeline = Pipeline(steps=[
    ('preprocessing', preprocessing_pipeline),
    ('standardization', standardization_pipeline)
])
