from sklearn.pipeline import Pipeline

from src.features.transformers import DateTimeTransformer, DropColumnsTransformer, ExtractColumnsTransformer, FillPropertyNaNsTransformer, GetDummiesTransformer, \
    PropertyOutlierTransformer, StandardScalerTransformer, DateTimeHourTransformer

columns_to_extract = [
    'p_num',
    'hour_sin',
    'hour_cos',
    'bg-0:00',
    'bg-0:05',
    'bg-0:10',
    'bg-0:15',
    'bg-0:20',
    'bg-0:25',
    'bg-0:30',
    'bg-0:35',
    'bg-0:40',
    'bg-0:45',
    'bg-0:50',
    'bg-0:55',
    'bg-1:00',
    'bg-1:05',
    'bg-1:10',
    'bg-1:15',
    'bg-1:20',
    'bg-1:25',
    'bg-1:30',
    'bg-1:35',
    'bg-1:40',
    'bg-1:45',
    'bg-1:50',
    'bg-1:55',
    'bg-2:00',
    'insulin-0:00',
    'insulin-0:05',
    'insulin-0:10',
    'insulin-0:15',
    'insulin-0:20',
    'insulin-0:25',
    'insulin-0:30',
    'insulin-0:35',
    'insulin-0:40',
    'insulin-0:45',
    'insulin-0:50',
    'insulin-0:55',
    'insulin-1:00',
    'insulin-1:05',
    'insulin-1:10',
    'insulin-1:15',
    'insulin-1:20',
    'insulin-1:25',
    'insulin-1:30',
    'insulin-1:35',
    'insulin-1:40',
    'insulin-1:45',
    'insulin-1:50',
    'insulin-1:55',
    'insulin-2:00',
    'cals-0:00',
    'cals-0:05',
    'cals-0:10',
    'cals-0:15',
    'cals-0:20',
    'cals-0:25',
    'cals-0:30',
    'cals-0:35',
    'cals-0:40',
    'cals-0:45',
    'cals-0:50',
    'cals-0:55',
    'cals-1:00',
    'cals-1:05',
    'cals-1:10',
    'cals-1:15',
    'cals-1:20',
    'cals-1:25',
    'cals-1:30',
    'cals-1:35',
    'cals-1:40',
    'cals-1:45',
    'cals-1:50',
    'cals-1:55',
    'cals-2:00',
    'hr-0:00',
    'hr-0:05',
    'hr-0:10',
    'hr-0:15',
    'hr-0:20',
    'hr-0:25',
    'hr-0:30',
    'hr-0:35',
    'hr-0:40',
    'hr-0:45',
    'hr-0:50',
    'hr-0:55',
    'hr-1:00',
    'hr-1:05',
    'hr-1:10',
    'hr-1:15',
    'hr-1:20',
    'hr-1:25',
    'hr-1:30',
    'hr-1:35',
    'hr-1:40',
    'hr-1:45',
    'hr-1:50',
    'hr-1:55',
    'hr-2:00',
    'steps-0:00',
    'steps-0:05',
    'steps-0:10',
    'steps-0:15',
    'steps-0:20',
    'steps-0:25',
    'steps-0:30',
    'steps-0:35',
    'steps-0:40',
    'steps-0:45',
    'steps-0:50',
    'steps-0:55',
    'steps-1:00',
    'steps-1:05',
    'steps-1:10',
    'steps-1:15',
    'steps-1:20',
    'steps-1:25',
    'steps-1:30',
    'steps-1:35',
    'steps-1:40',
    'steps-1:45',
    'steps-1:50',
    'steps-1:55',
    'steps-2:00',
    'bg+1:00'
]

preprocessing_pipeline = Pipeline(steps=[
    ('date_time', DateTimeHourTransformer(time_column='time', result_column='hour', type='sin_cos', drop_time_column=True)),
    ('drop_parameter_cols', DropColumnsTransformer(starts_with=['activity', 'carbs'])),
    ('drop_others', DropColumnsTransformer(columns_to_delete=['time'])),
    ('fill_properties_nan_bg', FillPropertyNaNsTransformer(parameter='bg', how=['interpolate', 'median'], interpolate=3, ffill=1, bfill=1, precision=1)),
    ('fill_properties_nan_insulin', FillPropertyNaNsTransformer(parameter='insulin', how=['interpolate', 'median'], interpolate=3, ffill=1, bfill=1, precision=4)),
    ('fill_properties_nan_cals', FillPropertyNaNsTransformer(parameter='cals', how=['interpolate', 'median'], interpolate=3, ffill=1, bfill=1, precision=1)),
    ('fill_properties_nan_hr', FillPropertyNaNsTransformer(parameter='hr', how=['interpolate', 'median'], interpolate=3, ffill=1, bfill=1, precision=1)),
    ('fill_properties_nan_steps', FillPropertyNaNsTransformer(parameter='steps', how=['zero'], interpolate=3, ffill=1, bfill=1, precision=1)),
    ('drop_outliers', PropertyOutlierTransformer(parameter='insulin', filter_function=lambda x: x < 0, fill_strategy='zero')),
    ('extract_features', ExtractColumnsTransformer(columns_to_extract=columns_to_extract)),
])

standardization_pipeline = Pipeline(steps=[
    ('get_dummies', GetDummiesTransformer(columns=['hour', 'p_num'])),
    ('standard_scaler', StandardScalerTransformer(columns=columns_to_extract[1:-1]))
])

pipeline = Pipeline(steps=[
    ('preprocessing', preprocessing_pipeline),
    ('standardization', standardization_pipeline)
])
